oam-dev/rudr

src/instigator.rs
src/schematic/component.rs
src/workload_type.rs
src/workload_type/worker.rs
src/workload_type/workload_builder.rs

This adds a new optional validation trait member for workload types, and implements the trait for the two worker types. Specifically, Rudr will throw an error if a worker tries to bind to a port, which is not allowed by the definition of `worker`.
Closes #323 

validate worker config before starting a worker

---

Makefile

This PR enables Docker CLI experimental features in order to create a manifest for container images. This will allow us to use a single tag inside the Helm chart that will work cross OS/architecture.
This PR also removes now obsolete docker-build target, as it would conflict with the tag for the manifest. We could keep `docker-build` target but drop `push` command if desired.
This PR also adds the `amd64` base container image names into the `docker-build-cx` target for symmetry so that images for all architectures are updated at the same time.
This will address #334.

Enable Docker CLI experimental features and cleanup Makefile

---

Makefile

Setting up the environment variable explicitly for lines that need it. Validated on my repo that this unblocks the experimental check.
This fixes #373.

Enable experimental CLI features on per command basis

---

charts/rudr/templates/rolebinding.yaml

Use `.Release.Namespace` in `ClusterRoleBinding` to support installing `rudr`
in a namespace other than `default`.

bug(serviceaccount): install rudr in other namespaces

---

docs/setup/install.md

we don't have `0.8.0`, only `v1.0.0-alpha.1`
https://cloud.docker.com/u/oamdev/repository/registry-1.docker.io/oamdev/rudr/tags

fix image tag in doc

---

charts/healthscope/templates/deployment.yaml

fix the first issue of #393 `Error: apiVersion "apps/v1beta2" in healthscope/templates/deployment.yaml is not available  `

fix charts deployment to apps/v1

---

examples/first-app-config.yaml

I add health scope to `first-app-config`, but if user didn't install healthscope instance first, they will fail, so I remove the healthscope dependency from `first-app-config`.
We should add health-scope in another  example
fixes #431

keep first-app-config without healthscope dependency

---

src/main.rs

This is a minor refactor that I encountered while hunting for issue #441. It just reduces the complexity of the code and adds an `info!` for in-cluster config loading.

refactor the kubeconfig() function

---

docs/how-to/create_component_from_scratch.md

This fixes #402 by adding a link to follow installation steps in the prereqs of this How-To

link to installation steps in how-to

---

charts/rudr/templates/traits.yaml

Now properties is [described as jsonschema in OAM](https://github.com/oam-dev/spec/blob/master/5.traits.md#properties)

make traits yaml file consistent with oam spec

---

.github/workflows/nightly.yml
Makefile

Now nightly build failed again cause it was running more than six hours. So I split them into two phases.
Also, I add health scope build into nightly GitHub action.

split build image into two nightly actions to reduce execute time

---

Dockerfile

Today I tracked down the source of the OpenSSL error in Rust, and figured out the problem. This cuts almost 30M (and a lot of time) off the build.

fix: set up openssl in newest stable Debian

---

docs/setup/install.md

Update installation docs for autoscaler trait now that we've shipped KEDA 1.0 with our new helm repo & chart name.
/cc @jeffhollan

Autoscaler trait - Update to use new KEDA chart & repo

---

README.md

- use recurring schedule.
- change it to 4:30pm per discussion with wonderflow and Sudhanva

Fix APAC meeting time

---

Dockerfile.e2e
Makefile

Dockerfile was refined in https://github.com/oam-dev/rudr/pull/466, but unfortunately we didn't change the base image used in Makefile, this cause our rudr image can't work #488 .
Our  e2e check didn't find it, because we didn't make the consistent.
fixes #488

fix inconsistent base image in Dockerfile and Makefile 

---

src/main.rs
src/schematic/traits/ingress.rs
src/schematic/traits/ingress_test.rs
src/schematic/traits/manual_scaler.rs

Issue: #477
If the values are provided as string, try converting them,
else add warning to the log and set it to default value.
This may not be needed if we add the validate the config schema using validation schema which is in the works.

Avoid silent conversion of service_port in ingress trait & replicaCount in manualscaler trait

---

docs/README.md

Find out the redundant comma while reading the docs, and this PR is going to fix this:
Thanks.

Removed redundant comma.

---

Cargo.lock
Cargo.toml
src/instigator.rs
src/kube_event.rs
src/lib.rs
src/main.rs

fixes #316 
This is a good start for rudr to add every important stage into kubenetes event. Then we could see the events from `kubectl describe` like below:
```
$ kubectl describe cfg first-app
Name:         first-app
Kind:         ApplicationConfiguration
...
Spec:
Components:
Component Name:  helloworld-python-v1
Instance Name:   first-app-helloworld-python-v1
...
Events:
Type     Reason                                                                                     Age   From  Message
----     ------                                                                                     ----  ----  -------
Warning  ApiError NotFound ("componentschematics.core.oam.dev \"helloworld-python-v1\" not found")  3s          creating AppConfig first-app error
```
```
$ kubectl describe cfg …
```

add k8s event record for rudr controller

---

docs/README.md

I have initialized [admission controller project](https://github.com/oam-dev/admission-controller).
Admission controller is used for mutating and validating OAM component, trait and application configuration spec.
fixes #349

add admission controller to docs

---

src/instigator.rs
src/schematic/traits/autoscaler.rs
src/schematic/traits/ingress.rs
src/workload_type/server.rs
src/workload_type/statefulset_builder.rs
src/workload_type/worker.rs
src/workload_type/workload_builder.rs

https://github.com/oam-dev/rudr/issues/514
The issue was that rudr was not reconciling it's state with the latest status.
If a deployment/svc/ing is deleted when the application confgiuration still exists, runtime doesn't recreate them. It detects those objects are not found but no action was taken.
The fix here is to recreate those objects back. The recreated objects have correct owner reference so no objects are orphaned.

Add reconciliation logic to get to the desired state for native K8s objects (deployment/svc/ing)

---

charts/rudr/templates/rolebinding.yaml

```shell script
$ kubectl apply -f examples/autoscaler.yaml 
applicationconfiguration.core.oam.dev/autoscaler-example created
$
$ kubectl get hpa
No resources found.
$
$ kubectl logs  rudr-95d869d47-2v855 -f
...
...
2020-03-10 03:52:34 INFO [rudr:src/main.rs:30] Loading in-cluster config
2020-03-10 03:52:43 INFO [rudr::instigator:src/instigator.rs:794] UID: 3a004bad-6283-11ea-9720-005056b75fab
2020-03-10 03:52:43 INFO [rudr::instigator:src/instigator.rs:602] MainControlLoop: Looking up workload for autoscaler-example <hpa-example-replicated-v1>
2020-03-10 03:52:43 INFO [rudr::instigator:src/instigator.rs:412] MainControlLoop: Adding component hpa-example-replicated-v1
2020-03-10 03:52:43 INFO [rudr::schematic::component:src/schematic/component.rs:188] Looking for image pull secret …
```

add apiGroups/autoscaling to clusterrole/rudr

---

README.md
docs/README.md

Minor change in messaging to make it clear that Rudr currently implements release 1.0.0-alpha1 of the spec.

Specifying that Rudr implements alpha 1 of the spec

---

charts/rudr/templates/traits.yaml
src/schematic/traits/ingress.rs
src/schematic/traits/ingress_test.rs

```
traits:
- name: ingress
properties:
hostname: example.com
path: /
servicePort: 9999
+            tlsHosts: example.com,www.example.com
+            tlsSecretName: mysecret
```
Closes issue #553

Adds TLS support for ingress trait.

---

README.md

I've got feedback from community users for v1alpha2 implementation. Due to the announcement is on-going, let's add a temporary redirect link in README.

Upgrade with temporary redirect link
