src/instigator.rs, src/main.rs, src/schematic/parameter.rs, src/schematic/traits.rs, src/schematic/traits/manual_scaler.rs, src/schematic/traits/volume_mounter.rs, src/trait_manager.rs
1. add patch retry incase of conflict happen. fixes #337
2. not update status when there's changes unfinshed. fixes #344
3. make cargo clippy happy
=> fix conflict on AppConfig object update

CONTRIBUTING.md, README.md, docs/concepts/application-configuration.md, docs/concepts/component-schematic.md, docs/concepts/traits.md, docs/concepts/using_rudr.md, docs/faq.md, docs/how-to/migrating.md
=> fix Hydra URLs

src/schematic/component.rs, src/schematic/component_test.rs
follow-up from #267
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
=> ref: remove to_deployment_spec

README.md
This adds the Actions badge to the README.
=> add GitHub Actions badge

docs/concepts/application-configuration.md, docs/concepts/component-schematic.md, docs/developer/writing_a_trait.md, governance.md
=> fixed URLs to point to the correct repo

README.md
=> an earlier not-quite-ready version was accidentally merged

examples/charts/README.md, examples/charts/hello-rudr/.helmignore, examples/charts/hello-rudr/Chart.yaml, examples/charts/hello-rudr/templates/NOTES.txt, examples/charts/hello-rudr/templates/_helpers.tpl, examples/charts/hello-rudr/templates/appconfig.yaml, examples/charts/hello-rudr/templates/component.yaml, examples/charts/hello-rudr/values.yaml
Had to re-open this PR from a new fork.
Closes #203
=> Add helm chart

README.md
=> add and fix links

docs/concepts/using_rudr.md
fix invalid link of Rudr tutorials
=> fix invalid link

README.md
Some grammar and typo changes that, I feel, make the README scan better.
=> Updates to README including language and typo fixes

docs/tutorials/deploy_and_update.md
=> fix invalid link to Using Rudr

Makefile
I needed to make some changes to get the Alpha.1 release built, so I just finished off a few other things and made the Makefile a little more configurable.
Closes #213 
=> Make the Makefile more configurable

CONTRIBUTING.md
=> update the info of CONTRIBUTING.md

docs/setup/install.md
=> Update install.md to add link to tutorials.

docs/concepts/application-configuration.md, docs/concepts/traits.md, docs/concepts/using_rudr.md, docs/tutorials/deploy_and_update.md, examples/autoscaler.yaml, examples/charts/hello-rudr/templates/appconfig.yaml, examples/env-vars.yaml, examples/first-app-config.yaml, examples/image-pull-secret.yaml, examples/manual-scaler.yaml, examples/multi-component.yaml, examples/multi-server.yaml, examples/replicable-task.yaml, examples/task.yaml, examples/volumes.yaml, examples/voting/configuration.yaml, examples/worker.yaml, healthscope/README.md, src/instigator.rs, src/instigator_test.rs, src/schematic/configuration.rs, src/schematic/configuration_test.rs, src/schematic/scopes/health.rs, src/trait_manager.rs
=> align components.name to components.componentName

docs/tutorials/deploy_and_update.md
=> change domain in Readme from example2.com to oamexample.com

docs/faq.md
=> fix migration guide link

docs/README.md, docs/how-to/manage_complicated_parameters.md, docs/how-to/using_helm_kustomize_manage_oam.md, examples/charts/hello-rudr/templates/appconfig.yaml, examples/kustomize/hello-rudr/base/appconfig.yaml, examples/kustomize/hello-rudr/base/component.yaml, examples/kustomize/hello-rudr/base/kustomization.yaml, examples/kustomize/hello-rudr/overlay/production/kustomization.yaml, examples/kustomize/hello-rudr/overlay/production/patch.yaml
=> docs: Using Helm/Kustomize to manage OAM yamls

docs/setup/install.md
This PR addresses the following issues:
- #399 
- #422 
- #401 
- I also found a nit where there was a repeated sentence which I deleted
=> setup instructions should have clone repo as first instruction

examples/singleton-nginx-config.yaml, src/instigator.rs, src/schematic/scopes/health.rs, src/workload_type.rs, src/workload_type/server.rs, src/workload_type/statefulset_builder.rs, src/workload_type/worker.rs, src/workload_type/workload_builder.rs
=> use statefulset instead of deployment to implement singleton worker and server

docs/concepts/component-schematic.md
=> add note about containers being scheduled on the same pod

examples/components.yaml, src/schematic/component.rs, src/schematic/component_test.rs
https://github.com/oam-dev/spec/blob/master/3.component_model.md#cpu
=> type of resource CPU & GPU should be float64

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> add github issuse template 

docs/tutorials/deploy_and_update.md
* Use `port-forward` to get the url. fixes #407
* Remove the hostname setting. fixes #420
=> remove the dependency of minikube and hostname setting

docs/README.md, docs/developer/debug.md, docs/developer/writing_a_trait.md
Now we don't have very good ways to debug, so I try to conclude some of my own way.
We could add more into this debug doc in the near future.
fixes #418
=> add debug doc for rudr

charts/waitForCRDs.sh
=> We have a lot of incoming CRDs in the ecosystem.  This is a nitpick.

README.md
fix https://github.com/oam-dev/rudr/issues/374
=> add rotating meeting schedule of Asian friendly time

docs/how-to/create_component_from_scratch.md, examples/charts/hello-rudr/templates/component.yaml, examples/helloworld-python-component.yaml, examples/kustomize/hello-rudr/base/component.yaml, examples/nginx-component.yaml
https://github.com/oam-dev/rudr/issues/476
spec.name shall be removed
=> removing component's spec.name fields

docs/setup/install.md
Few small fixes walking through the install info
=> Minor fixes to installation instructions

docs/concepts/component-schematic.md, docs/how-to/create_component_from_scratch.md, docs/how-to/using_helm_kustomize_manage_oam.md, examples/charts/hello-rudr/templates/component.yaml, examples/helloworld-python-component.yaml, examples/kustomize/hello-rudr/base/component.yaml, examples/nginx-component.yaml, examples/voting/components.yaml
This PR follows with https://github.com/oam-dev/rudr/pull/491
=> change ports:type to ports:protocol in all examples and docs

Makefile, charts/rudr/values.yaml, src/main.rs
In this issue https://github.com/oam-dev/rudr/issues/497 , we can't see error logs. It makes lots of confusion, so I add more logs.
=> add kube client logs in rudr

docs/tutorials/deploy_prometheus_workload.md
=> Fix yaml format in deploy_prometheus_workload.md

README.md, docs/README.md
Update the readme and documentation based on feedbacks from community.
=> Update the README of Rudr for key messages

src/instigator.rs
=> add control loop prefix to make log message clear

README.md, docs/README.md
=> Fix minor typos in doc

README.md
=> Update README with accurate narrative

README.md
No need to mention packaging tools, it's the scenarios for OAM, not Rudr
=> Remove packaging tools in why rudr

docs/concepts/traits.md
Refer to install doc for KEDA in trait docs rather than duplicating it
=> Refer to install doc for KEDA in trait docs

docs/concepts/component-schematic.md
=> Fixed link to Workload section

src/main.rs
after this PR merged, logs will look like below:
```
2020-01-31 13:31:13 INFO [rudr:src/main.rs:69] starting server
2020-01-31 13:31:13 INFO [rudr:src/main.rs:73] apiserver:https://192.168.64.3:8443
```
=> add module/file/line number in custom log

Makefile
In #539, We find it's hard to find out the reason why e2e is failed. So I add kubectl logs try to print out the reason.
=> print pod logs when helm install timeout

docs/faq.md
Fix #541 by making it part of FAQ.
=> Clarify knative relationship in detail

src/main.rs
=> delete unused component cache

docs/tutorials/deploy_and_update.md
=> docs: Traits should align with parameterValues

docs/how-to/create_component_from_scratch.md
=> doc: use diff codeblock instead of yaml

README.md
see https://github.com/oam-dev/rudr/issues/560
=> Polish 'README.md' (#560)
